spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: mypassword

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000  # 24 hours in milliseconds
  refresh-token:
    expiration: 604800000  # 7 days in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: health,info