server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

---
spring:
  config:
    activate:
      on-profile: discovery1
eureka:
  instance:
    hostname: discovery1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/

---
spring:
  config:
    activate:
      on-profile: discovery2
server:
  port: 8762
eureka:
  instance:
    hostname: discovery2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/

---
spring:
  config:
    activate:
      on-profile: discovery3
server:
  port: 8763
eureka:
  instance:
    hostname: discovery3
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/