server:
  port: 8040

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: sample-service
          uri: lb://sample-service
          predicates:
            - Path=/api/sample/**
          filters:
            - RewritePath=/api/sample/(?<path>.*), /api/sample/$\{path}
            
        - id: discovery-service-static
          uri: http://localhost:8061
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
            
        - id: discovery-service-resources
          uri: http://localhost:8061
          predicates:
            - Path=/eureka/**
          
management:
  endpoints:
    web:
      exposure:
        include: "*"