apiVersion: v1
kind: ConfigMap
metadata:
  name: config-repo
data:
  application.yml: |
    # Common configuration shared by all applications
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        health:
          show-details: ALWAYS 