apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-service-config
data:
  application.yml: |
    spring:
      application:
        name: discovery-service
      config:
        import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://config-service:8888} 