apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: microservice-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
      - name: discovery-service
        image: discovery-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://config-service:8888"
        
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: microservice-ns
spec:
  selector:
    app: discovery-service
  ports:
  - port: 8761
    targetPort: 8761 