apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-service-config
data:
  application.yml: |
    spring:
      application:
        name: sample-service
      config:
        import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://config-service:8888}
  application-instance1.yml: |
    server:
      port: 8081
    
    instance:
      name: sample-service-instance-1
    
    eureka:
      instance:
        instance-id: ${spring.application.name}:${instance.name}:${random.uuid}
        prefer-ip-address: true
      client:
        service-url:
          defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}
        register-with-eureka: true
        fetch-registry: true
  application-instance2.yml: |
    server:
      port: 8082
    
    instance:
      name: sample-service-instance-2
    
    eureka:
      instance:
        instance-id: ${spring.application.name}:${instance.name}:${random.uuid}
        prefer-ip-address: true
      client:
        service-url:
          defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}
        register-with-eureka: true
        fetch-registry: true 