apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service
  namespace: microservice-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-service
  template:
    metadata:
      labels:
        app: sample-service
    spec:
      containers:
      - name: sample-service
        image: sample-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8060
        env:
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://config-service:8888"
        readinessProbe:
          httpGet:
            path: /api/sample/actuator/health
            port: 8060
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /api/sample/actuator/health
            port: 8060
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: microservice-ns
spec:
  selector:
    app: sample-service
  ports:
  - port: 8060
    targetPort: 8060