version: '3.8'

services:
  config-service:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH-LOCATIONS=file:/config-repo
    volumes:
      - ./config-repo:/config-repo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  discovery1:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    hostname: discovery1
    ports:
      - "8761:8761"
    networks:
      - microservice-network
    depends_on:
      config-service:
        condition: service_healthy
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_PROFILES_ACTIVE=discovery1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  discovery2:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    hostname: discovery2
    ports:
      - "8762:8762"
    networks:
      - microservice-network
    depends_on:
      config-service:
        condition: service_healthy
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_PROFILES_ACTIVE=discovery2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8762/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  discovery3:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    hostname: discovery3
    ports:
      - "8763:8763"
    networks:
      - microservice-network
    depends_on:
      config-service:
        condition: service_healthy
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_PROFILES_ACTIVE=discovery3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8763/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  sample-service:
    build:
      context: ./sample-service
      dockerfile: Dockerfile
    ports:
      - "8081:8060"
    networks:
      - microservice-network
    depends_on:
      config-service:
        condition: service_healthy
      discovery1:
        condition: service_healthy
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery1:8761/eureka/,http://discovery2:8762/eureka/,http://discovery3:8763/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8080:8040"
    networks:
      - microservice-network
    depends_on:
      config-service:
        condition: service_healthy
      discovery1:
        condition: service_healthy
      sample-service:
        condition: service_healthy
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery1:8761/eureka/,http://discovery2:8762/eureka/,http://discovery3:8763/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8040/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  microservice-network:
    driver: bridge 