spring:
  application:
    name: sample-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}

server:
  port: 8082

instance:
  name: sample-service-instance-2