
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#      - ./migrations:/docker-entrypoint-initdb.d  # Optional: Load initial migrations

volumes:
  postgres_data:
    driver: local
